############################
# Services
############################
services:
  # ---------- MariaDB (Keycloak 用) ----------
  mariadb:
    container_name: mariadb
    image: mariadb:11.4.5
    networks: [back]
    expose: ["3306"]
    environment:
      MARIADB_ROOT_PASSWORD: mariadb_password
    volumes:
      - ./keycloak/sql:/docker-entrypoint-initdb.d
      - ./keycloak/my.cnf:/etc/mysql/my.cnf:ro
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ---------- Keycloak ----------
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2
    networks: [back, front]
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: -v start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      # DB 設定
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak_db_admin
      KC_DB_PASSWORD: "ahUJAw8,cEzO"

      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"

      TZ: Asia/Tokyo
      JAVA_OPTS_APPEND: -Duser.timezone=Asia/Tokyo
    restart: unless-stopped

  # ---------- Backend (FastAPI) ----------
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   env_file:
  #     - ./backend/.env
  #   networks: [front]
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     TZ: Asia/Tokyo
  #   depends_on:
  #     - keycloak
  #   restart: unless-stopped

  # ---------- Frontend (Vite + React) ----------
  frontend:
    container_name: frontend
    image: node:18-alpine
    networks: [front]
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      # ファイル変更検知を安定化
      CHOKIDAR_USEPOLLING: "true"
    command: >
      sh -c "
        npm ci &&
        npm run dev -- --host 0.0.0.0 --port 3000
      "
    restart: unless-stopped

############################
# Networks
############################
networks:
  front:
    driver: bridge
  back:
    driver: bridge

############################
# Volumes
############################
volumes:
  mariadb-data:
